name: My tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install
        run: make install
      - name: My tests
        run: make test